Debian dest reconfigured (#41)
* Namematching debian package update (#39)

* Fix tar error trying to set creator ids

* Update default namematching url in debian defaults to same value that Dockerfile one. SHA1 values updated

* Restart service after downloading

* Avoid namematching directory collision with other services. Lint fixes. And improve conf destinations

diff --git a/debian/ala-namematching-service.postinst b/debian/ala-namematching-service.postinst
--- a/debian/ala-namematching-service.postinst
+++ b/debian/ala-namematching-service.postinst
@@ -25,24 +25,27 @@ case "$1" in
         db_get ala-namematching-service/sha1
         SHA1=$RET
 
-        DEST=/data/lucene/namematching.tgz
+        DEST=/data/lucene/namematching-nm.tgz
+        FINAL_DEST=/data/lucene/namematching-nm/
 
         # To prevent /data/lucene installed nameindexes to fill our disk:
         #
         # 1) we try to not download the same nameindex again and again (this is why we use curl -C)
-        # 2) we rsync the tar over /data/lucene/namematching overwritting the previous nameindex
+        # 2) we rsync the tar over /data/lucene/namematching-nm overwritting the previous nameindex
         #
 
         echo "Downloading nameindex $URL ..."
 
-        # Try to resume previous download
-        curl -sLC - -o "$DEST" "$URL"
+        # Try to resume previous download (continue if fails)
+        set +e
+        curl -sLC - -o "$DEST" -f "$URL"
+        set -e
 
         SHA1_DOWNLOADED=$(sha1sum $DEST | awk '{ print $1 }')
 
         # Downloaded file sha1 does not match provided sha1, so retry full download
         if [[ "$SHA1" != "$SHA1_DOWNLOADED" ]]; then
-            echo "SHA1 does not match, trying to download again $URL ..."
+            echo "SHA1 does not match ($SHA1 vs $SHA1_DOWNLOADED), trying to download again $URL ..."
             curl -sL -o "$DEST" "$URL"
         fi
 
@@ -51,20 +54,27 @@ case "$1" in
         ROOTDIR2=$(tar tf $DEST | head -1 | cut -d "/" -f 2)
 
         echo "Untar nameindex source ..."
-        tar zxf $DEST -C /tmp/
+        tar zxf $DEST -C /tmp/ --no-same-owner
 
         if [[ -n "$ROOTDIR1" && ${#ROOTDIR1} -gt 1 ]]; then
             echo "Provided nameindex tar uses $ROOTDIR1 as root directory"
-            rsync -a --delete "/tmp/$ROOTDIR1/" /data/lucene/namematching/;
+            rsync -a --delete "/tmp/$ROOTDIR1/" "$FINAL_DEST";
         else
             if [[ -n "$ROOTDIR2" && ${#ROOTDIR2} -gt 1 ]]; then
                 echo "Provided nameindex tar uses $ROOTDIR2 as root directory"
-                rsync -a --delete "/tmp/$ROOTDIR2/" /data/lucene/namematching/;
+                rsync -a --delete "/tmp/$ROOTDIR2/" "$FINAL_DEST";
             else
                 echo "ERROR: Incorrect nameindex tar"
             fi
         fi
-        chown -R namematching:namematching /data/lucene/namematching/
+        chown -R namematching:namematching "$FINAL_DEST"
+
+        # Restart the service with the downloaded namematching
+
+        if [ -d /run/systemd/system ]; then
+            deb-systemd-invoke restart ala-namematching-service.service || true
+        fi
+
     ;;
 esac
 
